### ISSUE TITLE
Babel broken

### ISSUE THREAD

**Issue by ekkis** [i-rocky/country-list-js#6]
I've discovered a problem with the module, but not proper to the module itself

if the module is included into an environment that defines Object prototypes it breaks with the stack trace below.

the problem is that basically `babel-traverse` does shit like:
```javascript
for (var k in o) { // do stuff }
```
when it should do:
```javascript
for (var k in o) { if (o.hasOwnProperty(k)) { // do stuff }}
```
so I thought to patch their code but there are 633 open issues and 107 pull requests outstanding so I'd say the chance of fixing that is nil.  could we remove babel? after all, the only use of it is in the `import` which can easily be replaced with the older `require`

-- stack trace ---
```
/Users/ekkis/dev/country-list-js/node_modules/babel-core/lib/transformation/file/index.js:558
      throw err;
      ^

Error: /Users/ekkis/dev/country-list-js/src/index.js: You passed `traverse()` a visitor object with the property "ExportDeclaration" that has the invalid property "__test_function__"
    at verify (/Users/ekkis/dev/country-list-js/node_modules/babel-traverse/lib/visitors.js:205:17)
    at Object.explode (/Users/ekkis/dev/country-list-js/node_modules/babel-traverse/lib/visitors.js:72:3)
    at traverse (/Users/ekkis/dev/country-list-js/node_modules/babel-traverse/lib/index.js:77:12)
    at NodePath.traverse (/Users/ekkis/dev/country-list-js/node_modules/babel-traverse/lib/path/index.js:144:25)
    at Scope._crawl (/Users/ekkis/dev/country-list-js/node_modules/babel-traverse/lib/scope/index.js:828:10)
    at Scope.crawl (/Users/ekkis/dev/country-list-js/node_modules/babel-traverse/lib/scope/index.js:749:10)
    at Scope.init (/Users/ekkis/dev/country-list-js/node_modules/babel-traverse/lib/scope/index.js:744:32)
    at NodePath.setScope (/Users/ekkis/dev/country-list-js/node_modules/babel-traverse/lib/path/context.js:151:30)
    at NodePath.setContext (/Users/ekkis/dev/country-list-js/node_modules/babel-traverse/lib/path/context.js:166:8)
    at File._addAst (/Users/ekkis/dev/country-list-js/node_modules/babel-core/lib/transformation/file/index.js:497:8)
    at File.addAst (/Users/ekkis/dev/country-list-js/node_modules/babel-core/lib/transformation/file/index.js:505:10)
    at File.parseCode (/Users/ekkis/dev/country-list-js/node_modules/babel-core/lib/transformation/file/index.js:571:10)
    at /Users/ekkis/dev/country-list-js/node_modules/babel-core/lib/transformation/pipeline.js:49:12
    at File.wrap (/Users/ekkis/dev/country-list-js/node_modules/babel-core/lib/transformation/file/index.js:532:16)
    at Pipeline.transform (/Users/ekkis/dev/country-list-js/node_modules/babel-core/lib/transformation/pipeline.js:47:17)
    at Object.transformFileSync (/Users/ekkis/dev/country-list-js/node_modules/babel-core/lib/api/node.js:152:10)
    at compile (/Users/ekkis/dev/country-list-js/node_modules/babel-register/lib/node.js:118:20)
    at loader (/Users/ekkis/dev/country-list-js/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/ekkis/dev/country-list-js/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/ekkis/dev/country-list-js/test/index.test.js:9:17)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at loader (/Users/ekkis/dev/country-list-js/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/ekkis/dev/country-list-js/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at /Users/ekkis/dev/country-list-js/node_modules/mocha/lib/mocha.js:231:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/Users/ekkis/dev/country-list-js/node_modules/mocha/lib/mocha.js:228:14)
    at Mocha.run (/Users/ekkis/dev/country-list-js/node_modules/mocha/lib/mocha.js:514:10)
    at Object.<anonymous> (/Users/ekkis/dev/country-list-js/node_modules/mocha/bin/_mocha:480:18)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:774:12)
    at executeUserCode (internal/bootstrap/node.js:342:17)
    at startExecution (internal/bootstrap/node.js:276:5)
    at startup (internal/bootstrap/node.js:227:5)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
npm ERR! Test failed.  See above for more details.
```

**Comment by i-rocky** [comment]
I'm not really a Node.js person, I always go with babel. But I thought when you import the module in any system, the systems configuration transpiles the script? Shouldn't the babel configuration of the repository be ignored or overwritten?

**Comment by ekkis** [comment]
could we chat? are you on Telegram? I'm @ekkis there.  or we could meet on IRC?

**Comment by i-rocky** [comment]
I have a class right now. I do have telegram but not using at this point. I'll install it when I get back.

**Comment by ekkis** [comment]
ok.  ping me when you have a bit of time

**Comment by ekkis** [comment]
so, in fact, the only reason to run babel is for the tests.  I've ripped it all out but not being a big browserify guy I'm having issues making the `npm build` work.  it seems it's having a hard time minifying the code:
```
aprilis:country-list-js ekkis$ npm run-script build

> country-list-js@1.0.1 build /Users/ekkis/dev/country-list-js
> gulp

[20:38:37] Using gulpfile ~/dev/country-list-js/gulpfile.js
[20:38:37] Starting 'watch'...
[20:38:37] Finished 'watch' after 11 ms
[20:38:37] Starting 'compile'...

events.js:174
      throw er; // Unhandled 'error' event
      ^
GulpUglifyError: unable to minify JavaScript
    at createError (/Users/ekkis/dev/country-list-js/node_modules/gulp-uglify/lib/create-error.js:5:14)
    at /Users/ekkis/dev/country-list-js/node_modules/gulp-uglify/lib/minify.js:56:15
    at DestroyableTransform._transform (/Users/ekkis/dev/country-list-js/node_modules/gulp-uglify/composer.js:12:19)
    at DestroyableTransform.Transform._read (/Users/ekkis/dev/country-list-js/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/ekkis/dev/country-list-js/node_modul
```
in the `gulpfile.js` I took out line 2 `let babel = require('babelify');` which didn't seem to be used anyway, and in the `package.json` I removed all the dependencies on babel stuff and the "browserify" section, which only seemed to address babelify.  I also removed the `.babelrc`

help?

**Comment by ekkis** [comment]
in fact, gulp-browserify has been retired so we should yank it anyway: https://github.com/deepak1556/gulp-browserify

**Comment by ekkis** [comment]
ok, I figured out why it won't minify... uglify doesn't support => functions.  grr... the suggested solution is to babelise but since we're trying to get rid of babel, I'm going to have to convert all that pretty ES6 to old style :(

**Comment by ekkis** [comment]
I write for node in ES6.  the trouble with this particular package is the need for web support where it has to be browserified.  the minifier (uglify) doesn't know what to to with ES6

**Comment by ekkis** [comment]
what timezone are you in?

**Comment by ekkis** [comment]
I'd love to be able to keep the ES6

**Comment by ekkis** [comment]
ok.  I found the more modern `gulp-uglify-es` so I've rewritten the gulp file.  I get to keep my ES6 - yea! and we get to keep support for the browser.  see pull request

**Comment by i-rocky** [comment]
GitHub giving me notification about possible vulnerability of some package that are dependency of the devDependencies used in this package. How am I supposed to fix that!

**Comment by ekkis** [comment]
a vulnerability in devDependencies does not affect users of the package, only the package builder, so don't worry about it.  there are many packages out there that need fixing
